base_emb_dim: 6144
base_num_query_heads: 96
base_num_kv_heads: 8
base_mlp_dim: 6144
base_num_decoder_layers: 48
head_dim: 128
mlp_activations: ["relu","linear"]
vocab_size: 151808
enable_dropout: False
logits_via_embedding: False
normalization_layer_epsilon: 1.0e-5
num_experts: 16
num_experts_per_tok: 2
rope_max_timescale: 1_000_000
decoder_block: "mistral"